[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bunx prisma db push --accept-data-loss && bunx prisma generate && bun run db:seed && bun run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"
